apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world-container
        image: world:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
